config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/new'

  get 'tags/:tag', to: 'questions#index', as: :tag, :constraints  => { :tag => /[^\/]+/ }


  root 'questions#index'
  devise_for :users


  
  devise_scope :user do
    get 'signout', to: 'devise/sessions#destroy', as: :signout
  end

  resources :users, :only => :show, as: :user_profile
  resources :users, :only => :edit, as: :profile
  resources :users, :only => :update


  resources :questions do 
    resources :answers do 
      resources :comments
    end
  end

  get 'home', to: 'users#home'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  has_many :comments, as: :commentable, :dependent => :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, :dependent => :destroy
  belongs_to :user

  # for tags
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings



  def self.tagged_with(name)
    Tag.find_by!(name: name).questions
  end

  def self.tag_counts
    Tag.select("tags.id, tags.name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord

  # for tags 
  has_many :taggings
  has_many :questions, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :question
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :questions
  has_many :answers
  has_many :comments
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :set_answer, only: [:show, :create, :update, :destroy ]
  def index
    @answers = @question.answers
  end

  def show
    @commentable = @answer
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @answer = Answer.new
  end


  def create
    @answer = @question.answers.create(answer_params)
    @answer.user_id = current_user.id

    if @answer.save 
      redirect_to @answer.question
    else 
      render 'new'
    end
  end

  def edit
    
    @answer = @question.answers.find_by(id: params[:id])
  end

  def update
    
    @answer = @question.answers.find_by(id: params[:id])
    @answer.update_attributes(answer_params)

    redirect_to @question
  end

  def destroy
    @answer = @question.answers.find_by(id: params[:id])
    @answer.destroy
    
    redirect_to @question
  end

  private 

  def answer_params
    params.require(:answer).permit(:question_id, :content, :user_id)
  end
  
  # before_action :set_answer is making specific answer_id found and be accessable in entire answer class. 

  def set_answer
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  private
  
  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :school, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :school, :email, :password, :current_password) }
  end

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable
  before_action :set_comment
  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to [@question, @commentable], notice: "comment created"
    else
      render :new
    end
  end

private

  # def load_commentable
  #   resource, id = request.path.split('/')[1, 2]
  #   @commentable = resource.singularize.classify.constantize.find(id)
  # end

  def load_commentable
    klass = [Answer].detect {|c| params["#{c.name.underscore}_id"]}
    @commentable = klass.find(params["#{klass.name.underscore}_id"])
  end

  def set_comment
    @question = Question.find(params[:question_id])
    @commentable = @question.answers.find(params[:answer_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :commentable_id, :commentable_type)
    
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index

    @questions = if params[:tag]
      Question.tagged_with(params[:tag])

    else
      @questions = Question.all
    end
  end

  def show
    find_question

  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save

      redirect_to @question
    else
      render :new
    end
  end

  def edit
    find_question
  end

  def update
    @question = Question.find(params[:id]) 

    if @question.update_attributes(question_params)
      redirect_to @question
    else 
      render "edit"
    end
  end

  def destroy
    @question = Question.find_by(id: params[:id])
    @question.destroy

    redirect_to root_path
  end 

  private

  def question_params
    params.require(:question).permit(:subject_line, :description, :user_id, :tag_list)
    
  end

  def find_question
    @question = Question.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :school, :email, :password, :current_password)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / Integer(max.count) * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>campustechhub|%></title>
</head>
<body>
   <div id="comments">
  
    <%= answer.content %>
    <% if current_user && current_user.answers.include?(answer) %>
      <%= link_to "Edit", "/questions/#{@question.id}/answers/#{answer.id}/edit" %> 
      <%= link_to "Delete", "/questions/#{@question.id}/answers/#{answer.id}", method: :delete %>
    <% end %>
    <%= link_to "View Comments (#{answer.comments.size})", [@question, answer]%>
   </div>
</body>
</html>

app/views/answers/_form.html.erb
<div id="questions">
  <%= form_for [@question, @question.answers.build]  do |f| %>
    <%= f.text_area :content %><br><br>
    <%= f.hidden_field :question_id, value: "#{question_id = @question.id}" %>
    <%= f.submit "Your Answer" %>
  <% end %>
  
</div>

app/views/answers/edit.html.erb
<div id="questions">
  <%= form_for @answer, url: question_answer_path, method: :patch do |f| %>
    <%= f.text_area :content, value: "#{@answer.content}"%><br><br>
    <%= f.hidden_field :question_id, value: "#{question_id = @question.id}" %>
    <%= f.submit "Edit Your Answer" %>
  <% end %>
  
</div>

app/views/answers/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<div>
  <p id="questions">
   <%= @answer.content %>
  </p>
  
    <%= render "comments/comments" %>
    <%= render "comments/form" %>
</div>
</body>
</html>

app/views/comments/_comments.html.erb
<div>
  <p style="padding-left: 30px;">
    <% @comments.each do |comment| %>
      <%= simple_format comment.content%>
    <% end %>
  </p>

app/views/comments/_form.html.erb
<%= form_for [@question, @commentable, @comment]  do |f|%>
  <% if @comment.errors.any? %>
  <div>
    <h2> Please correct the following errors.</h2>
    <ul>
      <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

 <div>
   <%= f.text_area :content, rows: 8 %>
 </div>
 <div>
   <%= f.submit %>
 </div>
 <% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>
  <%= render 'comments' %>
  <%= link_to "New Comment", [:new, @question, @commentable, :comment] %>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CampusTechHub</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <link rel="stylesheet" href="http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css">
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">

  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="#"><img class="imagess" src="http://res.cloudinary.com/nexpals/image/upload/v1498737192/Nex-Pals-logo3_iifsxy.jpg"></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="navbar-collapse style= collapse in" id="bs-megadropdown-tabs" style="
      padding-left: 0px;
      ">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_url %>"><i class="fa fa-globe"></i> ALL</a></li>
        <li><a href="<%= questions_path %>"><i class="fa fa-university"></i> QUESTIONS</a></li>

       <!--  <li class="dropdown mega-dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-space-shuttle"></i> CATEGORIES <span class="caret"></span></a>               
         <div id="filters" class="dropdown-menu mega-dropdown-menu">
          <div class="container-fluid2"> -->
            <!-- Tab panes -->
           <!--  <div class="tab-content"> -->

<!-- 
              <div class="tab-pane active" id="kids">
                <ul class="nav-list list-inline">
                  <li><a data-filter=".89" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_Running.png"><span>BRICS</span></a></li>
                  <li><a data-filter=".97" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_Basketball.png"><span>Latin America</span></a></li>
                  <li><a data-filter=".96" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_Football.png"><span>USA</span></a></li>
                  <li><a data-filter=".87" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_Soccer.png"><span>Middle East</span></a></li>
                  <li><a data-filter=".85" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_MensTraining.png"><span>Asia</span></a></li>
                  <li><a data-filter=".90" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_MensTraining.png"><span>Africa</span></a></li>
                </ul>
              </div> -->
        <!--       <div class="tab-pane" id="sports">
                <ul class="nav-list list-inline">                                
                  <li><a data-filter=".38" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_Basketball.png"><span>Technology</span></a></li>
                  <li><a data-filter=".41" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_Football.png"><span>Music</span></a></li>
                  <li><a data-filter=".62" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_Soccer.png"><span>Startups</span></a></li>
                  <li><a data-filter=".82" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_MensTraining.png"><span>Celebrities</span></a></li>
                  <li><a data-filter=".93" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_WomensTraining.png"><span>Entertainment</span></a></li>
                  <li><a data-filter=".94" href="#"><img src="http://content.nike.com/content/dam/one-nike/globalAssets/menu_header_images/OneNike_Global_Nav_Icons_WomensTraining.png"><span>Series</span></a></li>
                </ul>
              </div>
            </div>
          </div> -->
          <!-- Nav tabs -->
        <!--   <ul class="nav nav-tabs" role="tablist">   
           <li   class="active"><a href="#kids" role="tab" data-toggle="tab">Countries</a></li>
           <li><a href="#sports" role="tab" data-toggle="tab">Top Guess</a></li>
         </ul>                    
       </div>              
     </li> -->
   </ul>
   <form class="navbar-form navbar-left" role="search">
    <div class="form-group">
      <input type="text" class="form-control" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-user"></span> 
        <% if user_signed_in? %>
          <strong ><%= "#{current_user.first_name} #{current_user.last_name}" %></strong>
        <% else %>
          <strong></strong>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
      </a>
      <ul style="background-color:white;" class="dropdown-menu">
        <li>
          <div class="navbar-login">
            <div class="row">
              <div class="col-lg-8">
                <p class="text-center">
                  <span class="glyphicon glyphicon-user icon-size"></span>
                </p>
              </div>
              <div class="col-lg-8">
              <% if user_signed_in? %>
                <p class="text-left"><strong ><%= "#{current_user.first_name} #{current_user.last_name}" %></strong></p>
                <p class="text-left small"> Email: <%= current_user.email %></p>
                 <p class="text-left small">School: <%= current_user.school %></p>
                <p class="text-left">
                <% end %>
                  <a href="" class="btn btn-primary btn-block btn-sm">Contributor</a>
                </p>
              </div>
            </div>
          </div>
        </li>
        <li class="divider"></li>
        <li>
          <div class="navbar-login navbar-login-session">
            <div class="row">
              <div class="col-lg-12">
                <p>
                  <a href="#" class="btn btn-danger btn-block">Desactivate my Account</a>
                </p>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </li>
    <li class="dropdown">
               <% if user_signed_in? %>
               <a style="float: right;" href="<%=signout_path%>">LOGOUT</a>
               <% else %>
              <!--  <a href="<%= new_user_session_path %>">Log In</a> -->
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">SIGN IN <span class="caret"></span></a>
      <ul id="login-dp" class="dropdown-menu">
        <li>
         <div class="row">
          <div class="col-md-12">
            Login via
            <div class="social-buttons">
              <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
              <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
            </div>
            or
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
              <div class="form-group">
               <label class="sr-only" for="exampleInputEmail2">Email address</label>
               <%= f.email_field :email, class: "form-control", id: "exampleInputEmail2", placeholder: "Email address" %>
             </div>
             <div class="form-group">
               <label class="sr-only" for="exampleInputPassword2">Password</label>
               <%= f.password_field :password, class: "form-control", id:"exampleInputPassword2", placeholder: "password", required: true %>
               <div class="help-block text-right"><a href="">Forget the password ?</a></div>
             </div>
             <div class="form-group">
               <button type="submit" class="btn btn-primary btn-block">Sign in</button>


             </div>
             <div class="checkbox">
               <label>
                 <input type="checkbox"> keep me logged-in
               </label>
             </div>
           </form>
           <% end %>
               <p class="notice"><%= notice %></p>
               <p class="alert"><%= alert %></p>
         </div>
         <div class="bottom text-center">
          New here ? <a href="#"><b>Join Us</b></a>
        </div>
      </div>
    </li>
  </ul>
</li>
               <% end %>
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<%= yield %>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question  do |f| %>
  <%= f.label :subject_line %><br>

  <%= f.text_field :subject_line %><br><br>
  
  <%= f.label :tag_list, "Tags(Separated by commas)" %><br>
  <%= f.text_field :tag_list %><br><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br><br>
  <%= f.submit %>
<% end %>


     <link href="https://fonts.googleapis.com/css?family=Oleo+Script:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Teko:400,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  
<section id="contact">
      <div class="section-content">
        <h1 class="section-header" style="margin-left: 300px; font-size: 28px;"><span class="content-header wow fadeIn " data-wow-delay="0.2s" data-wow-duration="2s"> Ask your Question...</span></h1>
       
      </div>
      <div class="contact-section">
      <div class="container">
        <form>
          <div class="col-md-4">
        <img src="https://cdn1.iconfinder.com/data/icons/softwaredemo/PNG/256x256/Pencil3.png" class="img-responsive center-block" alt="">
    </div>
    <div class="col-md-8" form-line">
              <div class="form-group">
                <label for="exampleInputUsername">Subject Line</label>
                <input type="text" class="form-control" id="" placeholder="Question Title...">
              </div>
              <div class="form-group">
                <label for="exampleInputEmail">Tag List</label>
                <input type="email" class="form-control" id="exampleInputEmail" placeholder=" Eg: Battery, Screen, ...">
              </div>  
          
            </div>
            <div class="col-md-8">
              <div class="form-group">
                <label for ="description"> Description</label>
                <textarea  class="form-control" id="description" placeholder="Details..."></textarea>
              </div>
              <div>

                <button type="button" class="btn btn-default submit"><i class="fa fa-paper-plane" aria-hidden="true"></i> Create Question </button>
              </div>
              
          </div>
        </form>
      </div>
    </section>

app/views/questions/_question.html.erb
<!-- !DOCTYPE html>
<html>
<head>
  <title></title>
</head> -->

<!-- <body>
  <div id="questions">
    <h2 class="subject_line">
      <%= link_to question.subject_line, question %><br>
    </h2>
      <%= simple_format question.description %>
    <p class="description">
      Tags: <%= raw question.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
    </p>
    
  </div>


</body> -->
<!-- </html> -->



    





<link href="https://fonts.googleapis.com/css?family=Josefin+Slab" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container" style="margin-top: 20px; margin-bottom: 20px;">
  <div class="row panel">
    
        <div class="col-md-8  col-xs-12">
           <img src="http://lorempixel.com/output/people-q-c-100-100-1.jpg" class="img-thumbnail picture hidden-xs" />
           <img src="http://lorempixel.com/output/people-q-c-100-100-1.jpg" class="img-thumbnail visible-xs picture_mob" />
           <div class="header">

            <div class="header" style="font-family: 'Josefin Slab', serif;">
              

    <h1 class="subject_line" style="font-size: 30px;">
      <%= link_to question.subject_line, question %>
    </h1>
       <span style="font-size: 16px;"><%= simple_format question.description %></span>
    <p class="description" style="font-size: 18px;">
      Tags: <%= raw question.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
    </p>
    

           </div>
               
           </div>
        </div>
    </div>   
    
  <div class="row nav">    
        <div class="col-md-4"></div>
        <div class="col-md-8 col-xs-12" style="margin: 0px;padding: 0px;">
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-weixin fa-lg"></i> 16</div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-heart-o fa-lg"></i> 14</div>
            <div class="col-md-4 col-xs-4 well"><i class="fa fa-thumbs-o-up fa-lg"></i> 26</div>
        </div>
    </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Josefin+Slab" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">


<button class="btn btn-success btn-block" style="width:200px; margin-left: 20px; background-color: #AFE7AA;"><span class="fa fa-plus-circle"></span><%= link_to "New Question", new_question_path%><br></button>
<% if user_signed_in? %>
   <button class="btn btn-info btn-block" style="width: 200px; margin-left: 20px; background-color: #AAE7DF;"><span class="fa fa-user"></span><%= link_to "User Profile",  user_profile_path(current_user) %></button>
<% end %>



<div class="container" style="margin-top: 20px; margin-bottom: 20px;">
  <div class="row panel">
    
        <div class="col-md-8  col-xs-12">
           
           <div class="header">

            <div class="header" style="font-family: 'Josefin Slab', serif;">
              

    <div id="tag_cloud" class="tags_banner" style="width: 300px; background-color: white; border-color: white; font-family: 'Josefin Slab', serif;">
  <h2> Tags: <% tag_cloud Question.tag_counts, %w[s m l] do |tag, css_class| %></h2>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
</div>
    

           </div>
               
           </div>
        </div>
    </div>   


    <%= render @questions.reverse %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<% if current_user && current_user.questions.include?(@question) %>
  <button class="btn btn-success btn-block" style="width:200px; margin-left: 20px; background-color: #AFE7AA;"><span class="fa fa-pencil"></span><%= link_to "Edit", edit_question_path(@question) %></button>
  <button class="btn btn-danger btn-block" style="width:200px; margin-left: 20px; background-color: #F8BFBF"><span class="fa fa-trash"></span><%= link_to "Delete", question_path, method: :delete%></button>
<% end %>
<%= render @question %>
<h4 id="questions">This question has got <%= @question.answers.count %> Answers</h4>
<%= render @question.answers %>
<%=  render '/answers/form' %>

app/views/users/home.html.erb
<div class="container">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="http://placehold.it/1200x400/16a085/ffffff&text=Guidlines">
                <div class="carousel-caption">
                    <h3>
                        How to post a Question</h3>
                    <p>
                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                        ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                </div>
            </div>
            <!-- End Item -->
            <div class="item">
               <img src="http://placehold.it/1200x400/e67e22/ffffff&text=Projects">
                <div class="carousel-caption">
                    <h3>
                        How to effiently use this website</h3>
                    <p>
                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                        ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                </div>
            </div>
            <!-- End Item -->
            <div class="item">
                <img src="http://placehold.it/1200x400/2980b9/ffffff&text=Benefits">
                <div class="carousel-caption">
                    <h3>
                        </h3>
                    <p>
                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                        ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                </div>
            </div>
            <!-- End Item -->
            <div class="item">
                <img src="http://placehold.it/1200x400/8e44ad/ffffff&text=Services">
                <div class="carousel-caption">
                    <h3>
                        Headline</h3>
                    <p>
                        Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                        ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                </div>
            </div>
            <!-- End Item -->
        </div>
        <!-- End Carousel Inner -->
        <ul class="nav nav-pills nav-justified">
            <li data-target="#myCarousel" data-slide-to="0" class="active"><a href="#">Guidlines<small></small></a></li>
            <li data-target="#myCarousel" data-slide-to="1"><a href="#">Earn a Badge<small></small></a></li>
            <li data-target="#myCarousel" data-slide-to="2"><a href="#">Benefits<small></small></a></li>
            <li data-target="#myCarousel" data-slide-to="3"><a href="#">Services<small></small></a></li>
        </ul>
    </div>
    <!-- End Carousel -->
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <h1 class="profile_body">User Profile</h1>
  <div class="user_profiles">
  <ul>
    <li>
      <strong> Full Name</strong>: <%= "#{@user.first_name} #{@user.last_name}"%>
    </li><br>
    <li>
      <strong>Email Address</strong>: <%= @user.email %>
    </li><br>

    <li>
      <strong>School</strong>: <%= @user.school %>
    </li>
  </ul>
    
  </div>

</body>
</html>